# Generated by Django 2.2 on 2019-10-26 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ID', models.IntegerField()),
                ('user_first_name', models.CharField(max_length=100)),
                ('user_last_name', models.CharField(max_length=100)),
                ('user_email', models.CharField(max_length=200)),
                ('user_DOB', models.DateField()),
                ('user_type', models.CharField(choices=[('Student', 'Student'), ('Staff', 'Staff')], max_length=100)),
            ],
        ),
    ]
