# Generated by Django 2.2 on 2019-11-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191102_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='color',
            field=models.CharField(max_length=100, null=True, verbose_name='vehicle color'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='photo',
            field=models.ImageField(null=True, upload_to='cars'),
        ),
    ]
